### ISSUE TITLE
MultiClock styles differ greatly from anything else put in the tray

### ISSUE THREAD

**Issue by mattgen88** [mibus/MultiClock#6]
MultiClock's text isn't vertically aligned middle, it seem to be top aligned. It also has opacity set. It looks nothing like any other tray item, including the existing clock. Is there any way to make it take on the existing styles so it doesn't look starkly different?

**Comment by mibus** [comment]
Vertical alignment is now fixed in GitHub, and I've uploaded a copy to extensions.gnome.org.

Feel free to reopen this with suggestions on distinguishing the clock better without it blending too harshly into the existing clock, it'd be nice to get something that works better for everyone!

**Comment by shuhaowu** [comment]
It still seems like the clock is misaligned in the verticle direction by 1 px. See the image here:

![untitled](https://user-images.githubusercontent.com/338100/52582250-c1eb2d80-2dfa-11e9-9c15-bc7511adc3c8.png)
