### ISSUE TITLE
Way to remove added timezones

### ISSUE THREAD

**Issue by jurosh** [mibus/MultiClock#9]
Current there is no way on UI to remove timezone.

Would be nice to have it - eg right click on list item.

**Comment by mibus** [comment]
Do you just mean for the default/included timezones or for ones you add yourself?

At most one custom one is retained long-term, the others will disappear after a restart.

If you're meaning including the default ones, it's not something I've time to work on but I'd accept PRs.

Thanks!

**Comment by jurosh** [comment]
Hey,
I think, I thought to at least provide external link to website which list
all timezones.  Eg thisone
https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones

Cheers,
Juraj

**Comment by jurosh** [comment]
Eh, sorry this list was for another report.

Yea, I probably meant custom ones.

**Comment by mibus** [comment]
OK, well (as noted) custom ones clean up after themselves eventually, so I'm going to leave it as-is.

(I don't think the built-in menu code can do things like right-clicks or sub-widgets, and I don't want to write a custom widget)

Thanks for the feedback!
